"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var express_1 = require("express");
var userController_1 = require("../controllers/userController");
var authMiddleware_1 = require("../middlewares/authMiddleware");
require("../strategies/githubStrategy");
var router = express_1.default.Router();
router.post("/", userController_1.create_user);
router.post("/login", userController_1.login_user);
router.patch("/confirm/:usertoken", userController_1.confirm_email);
router.post("/logout", authMiddleware_1.protect, userController_1.logout_user);
exports.default = router;
